"""initial migration

Revision ID: 584b0b8a4ba7
Revises: c16d792bf227
Create Date: 2024-04-22 14:56:16.224715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584b0b8a4ba7'
down_revision: Union[str, None] = 'c16d792bf227'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lol', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
